CC = g++
CFLAGS = -std=c++11 -w
DEPS = hw10.h

testmake: program0.cpp program1.cpp program2.cpp program3.cpp
	$(CC) $(CFLAGS) -o run program0.cpp
	$(CC) $(CFLAGS) -o p1 program1.cpp
	$(CC) $(CFLAGS) -o p2 program2.cpp
	$(CC) $(CFLAGS) -o p3 program3.cpp
	$(info ********** Run program with: /.run **********)
